# Generated by Django 2.1.5 on 2020-02-11 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categorys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='commercial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=25)),
                ('productName', models.TextField(null=True)),
                ('cat', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='commercial.categorys')),
            ],
        ),
        migrations.CreateModel(
            name='imageCommercial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imges', models.ImageField(blank=True, default='default.png', upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='commercial',
            name='img',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='commercial.imageCommercial'),
        ),
    ]
